[package]
name = "usdcc-token"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/00impera/usdcc-token"

[lib]
crate-type = ["cdylib"]

[dependencies]
near-sdk = "5.6.0"

[profile.release]
codegen-units = 1
opt-level = "z"
lto = true
debug = false
panic = "abort"
overflow-checks = true

[package.metadata.near.reproducible_build]
image = "sourcescan/cargo-near:0.13.5-rust-1.85.1"
image_digest = "sha256:3b0272ecdbb91465f3e7348330d7f2d031d27901f26fb25b4eaf1560a60c20f3"
container_build_command = ["cargo", "near", "build", "non-reproducible-wasm", "--locked"]
